default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: ${RAILS_APP_NAME}_development


test:
  <<: *default
  database: ${RAILS_APP_NAME}_test