default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: ${POSTGRES_USERNAME}
  password: ${POSTGRES_PASSWORD}
  pool: 5

development:
  <<: *default
  database: ${DATABASE_NAME}_development


test:
  <<: *default
  database: ${DATABASE_NAME}_test