default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: <%= ENV["POSTGRES_USERNAME"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  pool: 5

development:
  <<: *default
  database: <%= ENV["DATABASE_NAME"] %>_development


test:
  <<: *default
  database: <%= ENV["DATABASE_NAME"] %>_test